export const NOTIFICATION_BATCH_CONFIG = {
  MAX_CONCURRENT_REQUESTS: 10,
  RETRY_ATTEMPTS: 3,
  DELAY_BETWEEN_BATCHES_MS: 100,
  REQUEST_TIMEOUT_MS: 5000,
  MAX_PLAYERS_PER_ONESIGNAL_REQUEST: 2000,
} as const;